# Generated by Django 4.2 on 2025-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_vehiculo', models.CharField(max_length=200, verbose_name='Marca del vehiculo')),
                ('modelo_vehiculo', models.CharField(max_length=200, verbose_name='Modelo del vehiculo')),
                ('patente_vehiculo', models.CharField(max_length=200, verbose_name='Patente del vehiculo')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('imagenes', models.ImageField(upload_to=None, verbose_name='Imagenes del vehiculo')),
                ('modalidad', models.CharField(choices=[('particular', 'Particular'), ('terceros', 'Contra terceros'), ('riesgo', 'Contra todo riesgo'), ('recupero', 'Recupero de siniestro')], max_length=50, verbose_name='Modalidad de cobertura')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
        ),
    ]
