# Generated by Django 4.2 on 2025-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('telefono_cliente', models.CharField(max_length=200, verbose_name='Telefono del cliente')),
                ('marca_vehiculo', models.CharField(max_length=200, verbose_name='Marca del vehiculo')),
                ('modelo_vehiculo', models.CharField(max_length=200, verbose_name='Modelo del vehiculo')),
                ('patente_vehiculo', models.CharField(max_length=200, verbose_name='Patente del vehiculo')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='Imagenes/', verbose_name='Imagenes del vehiculo')),
                ('modalidad', models.CharField(choices=[('particular', 'Particular'), ('terceros', 'Contra terceros'), ('riesgo', 'Contra todo riesgo'), ('recupero', 'Recupero de siniestro')], max_length=50, verbose_name='Modalidad de cobertura')),
                ('estado', models.CharField(blank=True, choices=[('particular_uno', 'Alistar daños del vehiculo')], max_length=50, verbose_name='Estado')),
                ('trabajos_a_realizar', models.CharField(max_length=50, verbose_name='Trabajos a realizar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
            },
        ),
    ]
