# Generated by Django 4.2 on 2025-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nombre_cliente',
            field=models.CharField(default='x', max_length=200, verbose_name='Nombre del cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_cliente',
            field=models.CharField(default='212', max_length=200, verbose_name='Telefono del cliente'),
            preserve_default=False,
        ),
    ]
