# Generated by Django 4.2 on 2025-01-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='trabajos_a_realizar',
            field=models.TextField(verbose_name='Trabajos a realizar'),
        ),
    ]
