# Generated by Django 4.2 on 2025-01-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_orden_nombre_cliente_orden_telefono_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cliente',
        ),
    ]
