# Generated by Django 4.2 on 2025-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_remove_orden_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='Imagenes/', verbose_name='Imagenes del vehiculo'),
        ),
    ]
