# Generated by Django 4.2 on 2025-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_alter_orden_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('particular_uno', 'Alistar daños del vehiculo')], default='', max_length=50, verbose_name='Modalidad de cobertura'),
            preserve_default=False,
        ),
    ]
