# Generated by Django 4.2 on 2025-01-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='trabajos_a_realizar',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
