# Generated by Django 4.2 on 2025-01-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0006_orden_trabajos_a_realizar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='trabajos_a_realizar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
